### ISSUE TITLE
Cannot add classes to the extension configuration

### ISSUE THREAD

**Issue by Livijn** [GrahamCampbell/Laravel-Markdown#156] opened 2021-05-24 06:17 UTC
According to #154 you are supposed to add the extensions configuration to the `config/markdown.php`. However, when running `config:cache` in production you cannot have instances of classes in the config file since they are stringified.

I am using [Heading Permalink Extension](https://commonmark.thephpleague.com/1.6/extensions/heading-permalinks/#usage) and utilizing a custom slug generator which requires a class. Adding the class to the config returns an error.

My temporary solution was to just add this to my `AppServiceProvider`. This should either be documented, or maybe somehow fixed.

```php
        $markdownEnvironment = app()->make('markdown.environment');
        $markdownEnvironment->mergeConfig(['heading_permalink' => [
            'html_class' => '',
            'id_prefix' => 'content',
            'insert' => 'before',
            'title' => 'Permalink',
            'symbol' => '',
            'slug_normalizer' => new MarkdownSlugNormalizer(),
        ]]);
```

**Comment by GrahamCampbell** [comment] 2021-11-21 15:12
Thanks for the detailed issue report, and sorry for taking so long to get around to replying here. You are absolutely right - you should never put non-scalars/arrays in config. It needs to be serializable and lightweight. For this reason this is certainly not a bug, however we are lacking on the side of documentation here.

> $markdownEnvironment = app()->make('markdown.environment');

While this will work, I wouldn't recommend doing this, since this'll force resolve the environment on every request, even those that don't need to do things with markdown. The best thing to do here is to hook into Laravel's "resolving" event for that class, and add your stuffs to it at that point. :)

In your app service provider's register method, put the following:

```php
    $this->callAfterResolving('markdown.environment', function ($environment) {
        $environment->mergeConfig(['heading_permalink' => [
            'html_class' => '',
            'id_prefix' => 'content',
            'insert' => 'before',
            'title' => 'Permalink',
            'symbol' => '',
            'slug_normalizer' => new MarkdownSlugNormalizer(),
        ]]);
    });
```

Laravel uses this method behind the scenes a lot, to make sure we have startup times, only loading services when we need them. I'd encourage you to take a look at https://github.com/laravel/framework/blob/8.x/src/Illuminate/Support/ServiceProvider.php. You'll see that this method is smart. If the class has already been resolved, it immediately executes the callback code. Otherwise, it'll execute it when the class is first resolved. :)

**Closed as completed by GrahamCampbell** 2021-11-21 15:12 UTC
